@startuml holo

entity produto{
    *SKU <<PK>> : VARCHAR
    --
    nome : VARCHAR
    quantidade : INT
    dataValidade : DATE
}

entity lanche{
    *nome <<PK>> : VARCHAR
    --
    preco : NUMERIC
}

entity receita{
    *id <<PK>> : INT
}

entity passo{
    *id <<PK>> : INT
    receita <<FK>> : INT
    --
    passo : TEXT
}

receita ||--|{ passo

@enduml