INSERT INTO cliente (endereco, nome, genero, idade) VALUES ('Rua A, 123', 'Alice', 'F', 30);
INSERT INTO cliente (endereco, nome, genero, idade) VALUES ('Av. B, 456', 'Bruno', 'M', 25);
INSERT INTO cliente (endereco, nome, genero, idade) VALUES ('Praça C, 789', 'Carla', 'F', 28);
INSERT INTO cliente (endereco, nome, genero, idade) VALUES ('Rua D, 321', 'David', 'M', 35);
INSERT INTO cliente (endereco, nome, genero, idade) VALUES ('Av. E, 654', 'Elena', 'F', 22);
INSERT INTO cliente (endereco, nome, genero, idade) VALUES ('Rua F, 987', 'Felipe', 'M', 40);
INSERT INTO cliente (endereco, nome, genero, idade) VALUES ('Travessa G, 147', 'Gabriela', 'F', 27);
INSERT INTO cliente (endereco, nome, genero, idade) VALUES ('Rua H, 258', 'Henrique', 'M', 31);
INSERT INTO cliente (endereco, nome, genero, idade) VALUES ('Av. I, 369', 'Isabela', 'F', 29);
INSERT INTO cliente (endereco, nome, genero, idade) VALUES ('Rua J, 159', 'Jorge', 'M', 26);
INSERT INTO cliente (endereco, nome, genero, idade) VALUES ('Praça K, 753', 'Karine', 'F', 33);
INSERT INTO cliente (endereco, nome, genero, idade) VALUES ('Rua L, 852', 'Lucas', 'M', 24);
INSERT INTO cliente (endereco, nome, genero, idade) VALUES ('Av. M, 951', 'Mariana', 'F', 32);
INSERT INTO cliente (endereco, nome, genero, idade) VALUES ('Rua N, 159', 'Nicolas', 'M', 36);
INSERT INTO cliente (endereco, nome, genero, idade) VALUES ('Praça O, 357', 'Olivia', 'F', 23);

INSERT INTO administrador (email, senha) VALUES ('admin1@example.com', 'senha123');
INSERT INTO administrador (email, senha) VALUES ('admin2@example.com', 'senha456');
INSERT INTO administrador (email, senha) VALUES ('admin3@example.com', 'senha789');
INSERT INTO administrador (email, senha) VALUES ('admin4@example.com', 'senha101');
INSERT INTO administrador (email, senha) VALUES ('admin5@example.com', 'senha202');
INSERT INTO administrador (email, senha) VALUES ('admin6@example.com', 'senha303');
INSERT INTO administrador (email, senha) VALUES ('admin7@example.com', 'senha404');
INSERT INTO administrador (email, senha) VALUES ('admin8@example.com', 'senha505');
INSERT INTO administrador (email, senha) VALUES ('admin9@example.com', 'senha606');
INSERT INTO administrador (email, senha) VALUES ('admin10@example.com', 'senha707');
INSERT INTO administrador (email, senha) VALUES ('admin11@example.com', 'senha808');
INSERT INTO administrador (email, senha) VALUES ('admin12@example.com', 'senha909');
INSERT INTO administrador (email, senha) VALUES ('admin13@example.com', 'senha111');
INSERT INTO administrador (email, senha) VALUES ('admin14@example.com', 'senha222');
INSERT INTO administrador (email, senha) VALUES ('admin15@example.com', 'senha333');

INSERT INTO categoria (nome) VALUES ('Festa');
INSERT INTO categoria (nome) VALUES ('Casamento');
INSERT INTO categoria (nome) VALUES ('Aniversário');
INSERT INTO categoria (nome) VALUES ('Conferência');
INSERT INTO categoria (nome) VALUES ('Show');
INSERT INTO categoria (nome) VALUES ('Festival');
INSERT INTO categoria (nome) VALUES ('Jantares');
INSERT INTO categoria (nome) VALUES ('Exposição');
INSERT INTO categoria (nome) VALUES ('Workshop');
INSERT INTO categoria (nome) VALUES ('Encontro');
INSERT INTO categoria (nome) VALUES ('Feira');
INSERT INTO categoria (nome) VALUES ('Sarau');
INSERT INTO categoria (nome) VALUES ('Baile');
INSERT INTO categoria (nome) VALUES ('Competição');
INSERT INTO categoria (nome) VALUES ('Jogos');

INSERT INTO lista_categoria (pk_categoria, pk_evento) VALUES (1, 1);
INSERT INTO lista_categoria (pk_categoria, pk_evento) VALUES (2, 2);
INSERT INTO lista_categoria (pk_categoria, pk_evento) VALUES (3, 3);
INSERT INTO lista_categoria (pk_categoria, pk_evento) VALUES (4, 4);
INSERT INTO lista_categoria (pk_categoria, pk_evento) VALUES (5, 5);
INSERT INTO lista_categoria (pk_categoria, pk_evento) VALUES (6, 6);
INSERT INTO lista_categoria (pk_categoria, pk_evento) VALUES (7, 7);
INSERT INTO lista_categoria (pk_categoria, pk_evento) VALUES (8, 8);
INSERT INTO lista_categoria (pk_categoria, pk_evento) VALUES (9, 9);
INSERT INTO lista_categoria (pk_categoria, pk_evento) VALUES (10, 10);
INSERT INTO lista_categoria (pk_categoria, pk_evento) VALUES (11, 11);
INSERT INTO lista_categoria (pk_categoria, pk_evento) VALUES (12, 12);
INSERT INTO lista_categoria (pk_categoria, pk_evento) VALUES (13, 13);
INSERT INTO lista_categoria (pk_categoria, pk_evento) VALUES (14, 14);
INSERT INTO lista_categoria (pk_categoria, pk_evento) VALUES (15, 15);

INSERT INTO evento (nome, data, local, pk_administrador) VALUES ('Festa de Aniversário', '2024-10-01', 'Salão A', 1);
INSERT INTO evento (nome, data, local, pk_administrador) VALUES ('Conferência de Tecnologia', '2024-11-05', 'Auditório B', 2);
INSERT INTO evento (nome, data, local, pk_administrador) VALUES ('Show de Música', '2024-12-15', 'Estádio C', 3);
INSERT INTO evento (nome, data, local, pk_administrador) VALUES ('Exposição de Arte', '2024-10-20', 'Galeria D', 4);
INSERT INTO evento (nome, data, local, pk_administrador) VALUES ('Workshop de Culinária', '2024-11-10', 'Cozinha E', 5);
INSERT INTO evento (nome, data, local, pk_administrador) VALUES ('Festa Junina', '2024-06-25', 'Praça F', 6);
INSERT INTO evento (nome, data, local, pk_administrador) VALUES ('Baile de Formatura', '2024-12-01', 'Salão G', 7);
INSERT INTO evento (nome, data, local, pk_administrador) VALUES ('Feira de Negócios', '2024-10-15', 'Centro de Convenções H', 8);
INSERT INTO evento (nome, data, local, pk_administrador) VALUES ('Sarau Literário', '2024-11-20', 'Biblioteca I', 9);
INSERT INTO evento (nome, data, local, pk_administrador) VALUES ('Competição Esportiva', '2024-09-30', 'Quadra J', 10);
INSERT INTO evento (nome, data, local, pk_administrador) VALUES ('Aniversário da Cidade', '2024-10-05', 'Praça K', 11);
INSERT INTO evento (nome, data, local, pk_administrador) VALUES ('Caminhada Ecológica', '2024-11-15', 'Parque L', 12);
INSERT INTO evento (nome, data, local, pk_administrador) VALUES ('Festival Gastronômico', '2024-12-10', 'Centro M', 13);
INSERT INTO evento (nome, data, local, pk_administrador) VALUES ('Encontro de Amigos', '2024-11-25', 'Bar N', 14);
INSERT INTO evento (nome, data, local, pk_administrador) VALUES ('Lançamento de Livro', '2024-10-30', 'Auditório O', 15);

INSERT INTO cliente_evento (pk_cliente, pk_evento) VALUES (1, 1);
INSERT INTO cliente_evento (pk_cliente, pk_evento) VALUES (2, 2);
INSERT INTO cliente_evento (pk_cliente, pk_evento) VALUES (3, 3);
INSERT INTO cliente_evento (pk_cliente, pk_evento) VALUES (4, 4);
INSERT INTO cliente_evento (pk_cliente, pk_evento) VALUES (5, 5);
INSERT INTO cliente_evento (pk_cliente, pk_evento) VALUES (6, 6);
INSERT INTO cliente_evento (pk_cliente, pk_evento) VALUES (7, 7);
INSERT INTO cliente_evento (pk_cliente, pk_evento) VALUES (8, 8);
INSERT INTO cliente_evento (pk_cliente, pk_evento) VALUES (9, 9);
INSERT INTO cliente_evento (pk_cliente, pk_evento) VALUES (10, 10);
INSERT INTO cliente_evento (pk_cliente, pk_evento) VALUES (11, 11);
INSERT INTO cliente_evento (pk_cliente, pk_evento) VALUES (12, 12);
INSERT INTO cliente_evento (pk_cliente, pk_evento) VALUES (13, 13);
INSERT INTO cliente_evento (pk_cliente, pk_evento) VALUES (14, 14);
INSERT INTO cliente_evento (pk_cliente, pk_evento) VALUES (15, 15);
