@startchen

entity Pessoa{
id <<key>>
nome
cpf
matrícula
endereço
}

entity Aluno{

}

entity Professor{
titula
}

entity Curso{
id <<key>>
nome
area
}

entity Disciplina{
}

entity Sala{
id <<key>>
nome
capacidade
}

entity Turma{
}

relationship Cursa{
}

relationship Ministra{
}

relationship Local{
}

relationship Possui{
}

relationship FazParte{
id <<key>>
}

relationship Participa{
}

Pessoa ->- o { Aluno, Professor }

Aluno -N- Cursa
Curso -1- Cursa

Professor -1- Ministra
Disciplina -(0,N)- Ministra

Disciplina -(0,N)- Local
Sala -1- Local

Turma -(0,N)- Possui
Curso -1- Possui

Curso -(1,N)- FazParte
Disciplina -(1,N)- FazParte

Aluno -(0,N)- Participa
Turma -1- Participa

@endchen