@startuml Instituição Financeira

entity metas{
    *pk_metas INTEGER <<PK>> NOT NULL
    pk_funcionario <<FK>> NOT NULL
    --
    seguros_vendidos INTEGER
    contas_abertas INTEGER
    financiamentos INTEGER
    emprestimos_realizados INTEGER
}

entity funcionario{
    *pk_funcionario INTEGER <<PK>> NOT NULL
    --
    nome VARCHAR(100)
    gerente BOOL
}

metas |o--|| funcionario

@enduml