@startchen

entity jogadores{
id <<key>>
nome
N de contrato
tipo contrato
publicação
data inicio
apelido
nascimento
endereco
}

entity equipe{
id <<key>>
nome
}

entity partida{
id <<key>>
data

relationship joga{
}

relationship participa{
}

jogadores -(0,n)- participa
equipe -1- participa
equipe -2- joga
partida -(0,n)- joga
@endchen