CREATE TABLE
    participante (
        pk_participante NUMBER (10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        nome VARCHAR2 (100) NOT NULL,
        idade INTEGER CHECK (idade >= 0) NOT NULL,
        genero VARCHAR2 (2) NOT NULL,
        renda NUMERIC CHECK (renda >= 0) NOT NULL,
        regiao CHAR(2) NOT NULL,
        endereco VARCHAR2(256) NOT NULL
    );

CREATE TABLE
    pesquisa (
        pk_pesquisa NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        nome VARCHAR2(100) NOT NULL,
        data DATE NOT NULL
    );

CREATE TABLE
    produto (
        pk_produto NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        nome VARCHAR2(100) NOT NULL,
        data DATE NOT NULL,
        pk_pesquisa REFERENCES pesquisa
    );

CREATE TABLE
    questao (
        pk_questao NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        questao VARCHAR2(256) NOT NULL,
        tipo CHAR(1) NOT NULL,
        pk_pesquisa REFERENCES pesquisa
    );

CREATE TABLE
    likert (
        pk_likert NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        pk_questao REFERENCES questao,
        pk_participante REFERENCES participante,
        resposta NUMBER(2) CHECK (
            resposta >= 1
            OR resposta < 6
        ) NOT NULL
    );

CREATE TABLE
    texto (
        pk_texto NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        pk_questao REFERENCES questao,
        pk_participante REFERENCES participante,
        resposta VARCHAR2(256) NOT NULL
    );

CREATE TABLE
    pesquisa_participante (
        pk_pesquisa_participante NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        pk_pesquisa REFERENCES pesquisa NOT NULL,
        pk_participante REFERENCES participante NOT NULL
    );

INSERT INTO pesquisa(nome,data) VALUES ('Sabor produto',date'2024-11-11');

INSERT INTO questao(questao,tipo,pk_pesquisa) VALUES ('O sabor é bom?',0,1)
INSERT INTO questao(questao,tipo,pk_pesquisa) VALUES ('Gostou?',0,1);
INSERT INTO questao(questao,tipo,pk_pesquisa) VALUES ('1 a 5: comer?',0,1); 
INSERT INTO questao(questao,tipo,pk_pesquisa) VALUES ('Escala comeria de novo',0,1);
INSERT INTO questao(questao,tipo,pk_pesquisa) VALUES ('Sim ou não',0,1); 
INSERT INTO questao(questao,tipo,pk_pesquisa) VALUES ('food scale',0,1);
INSERT INTO questao(questao,tipo,pk_pesquisa) VALUES ('COMER bo?',1,1);
INSERT INTO questao(questao,tipo,pk_pesquisa) VALUES ('Diga se é bom',1,1);
INSERT INTO questao(questao,tipo,pk_pesquisa) values ('Bueno?',0,1);
INSERT INTO questao(questao,tipo,pk_pesquisa) values ('Goid?',0,1);

INSERT INTO pesquisa(nome,data) VALUES ('O futuro',date'2024-12-12');

INSERT INTO participante(nome, idade, genero, renda, regiao, endereco) 
VALUES ('Carlos Eduardo Bonel Dias', 19, 'H', 0.00, 'RS', 'Lajeado, Rua dos Bobos, Nº0');


INSERT INTO participante(nome, idade, genero, renda, regiao, endereco) 
VALUES ('João Lauro', 19, 'H', 0.00, 'RS', 'Cachoeira do Sul, Rua muito legal Nº2 apto 102');

INSERT INTO participante(nome, idade, genero, renda, regiao, endereco) 
VALUES ('Leonardo "Dominick" Machado', 19, 'NB', 2043.48, 'RS', 'Xangrilá, Rua StereoBlitchs, Nº196');

INSERT INTO participante(nome, idade, genero, renda, regiao, endereco) 
VALUES ('Carlas Eduarda Bonela Dias', 48, 'M', 10542.23, 'AM', 'CarlosPólis, Rua Beré, Nº489239');

INSERT INTO participante(nome, idade, genero, renda, regiao, endereco) 
VALUES ('João Teste da Silva', 65, 'H', 4925.42, 'SP', 'São Paulo, Rua João Almeida, Nº49');

INSERT INTO participante(nome, idade, genero, renda, regiao, endereco) VALUES ('Alice Souza', 28, 'M', 3000.00, 'SC', 'Rua A, 123');
INSERT INTO participante(nome, idade, genero, renda, regiao, endereco) VALUES ('Bruno Lima', 35, 'H', 4500.00, 'RS', 'Avenida B, 456');
INSERT INTO participante(nome, idade, genero, renda, regiao, endereco) VALUES ('Carla Mendes', 22, 'M', 2500.00, 'AM', 'Rua C, 789');
INSERT INTO participante(nome, idade, genero, renda, regiao, endereco) VALUES ('Daniel Costa', 30, 'H', 4000.00, 'RS', 'Praça D, 321');
INSERT INTO participante(nome, idade, genero, renda, regiao, endereco) VALUES ('Eduarda Ferreira', 27, 'M', 3500.00, 'MT', 'Rua E, 654');
INSERT INTO participante(nome, idade, genero, renda, regiao, endereco) VALUES ('Felipe Rocha', 40, 'H', 5000.00, 'AM', 'Avenida F, 987');
INSERT INTO participante(nome, idade, genero, renda, regiao, endereco) VALUES ('Giovana Silva', 34, 'M', 4200.00, 'RJ', 'Rua G, 234');
INSERT INTO participante(nome, idade, genero, renda, regiao, endereco) VALUES ('Henrique Almeida', 29, 'H', 3800.00, 'RJ', 'Praça H, 876');
INSERT INTO participante(nome, idade, genero, renda, regiao, endereco) VALUES ('Isabela Santos', 26, 'M', 3100.00, 'RJ', 'Rua I, 543');
INSERT INTO participante(nome, idade, genero, renda, regiao, endereco) VALUES ('Joaquim Pereira', 33, 'H', 4600.00, 'RR', 'Avenida J, 210');

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (1, 1, 3);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (1, 2, 4);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (1, 3, 2);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (1, 4, 5);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (1, 5, 1);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (1, 6, 4);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (2, 1, 2);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (2, 2, 5);


INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (2, 3, 3);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (2, 4, 1);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (2, 5, 4);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (2, 6, 2);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (3, 1, 5);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (3, 2, 3);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (3, 3, 4);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (3, 4, 2);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (3, 5, 5);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (3, 6, 1);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (4, 1, 1);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (4, 2, 2);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (4, 3, 3);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (4, 4, 4);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (4, 5, 5);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (4, 6, 3);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (5, 1, 4);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (5, 2, 1);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (5, 3, 5);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (5, 4, 2);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (5, 5, 4);

INSERT INTO likert (pk_questao, pk_participante, resposta) 
VALUES (5, 6, 1);

    INSERT INTO produto(nome, DATA,PK_PESQUISA) 
    VALUES ('Produto A', date'2024-11-05', 1);

    INSERT INTO produto(nome, DATA,PK_PESQUISA) 
    VALUES ('Produto B', date'2024-11-05', 2);

    INSERT INTO produto(nome, DATA,PK_PESQUISA) 
    VALUES ('Produto C', date'2024-11-05', 1);

    INSERT INTO produto(nome, DATA,PK_PESQUISA)  
    VALUES ('Produto D', date'2024-11-05', 1);

    INSERT INTO produto(nome, DATA,PK_PESQUISA) 
    VALUES ('Produto E', date'2024-11-05', 1);

    INSERT INTO produto(nome, DATA,PK_PESQUISA)  
    VALUES ('Produto F', date'2024-11-05', 1);

    INSERT INTO produto(nome, DATA,PK_PESQUISA) 
    VALUES ('Produto G', date'2024-11-05', 1);

    INSERT INTO produto(nome, DATA,PK_PESQUISA) 
    VALUES ('Produto H', date'2024-11-05', 1);

    INSERT INTO produto(nome, DATA,PK_PESQUISA) 
    VALUES ('Produto I', date'2024-11-05', 1);

    INSERT INTO produto(nome, DATA,PK_PESQUISA) 
    VALUES ('Produto J', date'2024-11-05', 1);

    INSERT INTO produto(nome, DATA,PK_PESQUISA) 
    VALUES ('Produto K', date'2024-11-05', 1);

    INSERT INTO produto(nome, DATA,PK_PESQUISA) 
    VALUES ('Produto L', date'2024-11-05', 1);

    INSERT INTO produto(nome, DATA,PK_PESQUISA) 
    VALUES ('Produto M', date'2024-11-05', 1);

    INSERT INTO produto(nome, DATA,PK_PESQUISA) 
    VALUES ('Produto N', date'2024-11-05', 1);

    INSERT INTO produto(nome, DATA,PK_PESQUISA) 
    VALUES ('Produto O', date'2024-11-05', 1);

    INSERT INTO produto(nome, DATA,PK_PESQUISA) 
    VALUES ('Produto P', date'2024-11-05', 1);

    INSERT INTO produto(nome, DATA,PK_PESQUISA) 
    VALUES ('Produto Q', date'2024-11-05', 1);

    INSERT INTO produto(nome, DATA,PK_PESQUISA) 
    VALUES ('Produto R', date'2024-11-05', 1);

    INSERT INTO produto(nome, DATA,PK_PESQUISA) 
    VALUES ('Produto S', date'2024-11-05', 1);

    INSERT INTO produto(nome, DATA,PK_PESQUISA) 
    VALUES ('Produto T', date'2024-11-05', 1);

INSERT INTO texto(pk_questao, PK_PARTICIPANTE, resposta) 
VALUES (1, 1, 'Não');

INSERT INTO texto(pk_questao, PK_PARTICIPANTE, resposta) 
VALUES (1, 2, 'Não');

INSERT INTO texto(pk_questao, PK_PARTICIPANTE, resposta) 
VALUES (3, 3, 'Não');

INSERT INTO texto(pk_questao, PK_PARTICIPANTE, resposta) 
VALUES (3, 4, 'Sim');

INSERT INTO texto(pk_questao, PK_PARTICIPANTE, resposta) 
VALUES (5, 5, 'Sim. Eu senti uma epifania religiosa, é como se eu fizesse parte de uma consciência coletiva que está experienciando a si mesma. Agora temos o Tom com a previsão do tempo.');

INSERT INTO texto(pk_questao, pk_participante, resposta) VALUES (1, 6, 'sim');
INSERT INTO texto(pk_questao, pk_participante, resposta) VALUES (2, 6, 'não');
INSERT INTO texto(pk_questao, pk_participante, resposta) VALUES (3, 6, 'sim');
INSERT INTO texto(pk_questao, pk_participante, resposta) VALUES (4, 8, 'não');
INSERT INTO texto(pk_questao, pk_participante, resposta) VALUES (5, 8, 'sim');
INSERT INTO texto(pk_questao, pk_participante, resposta) VALUES (6, 8, 'não');
INSERT INTO texto(pk_questao, pk_participante, resposta) VALUES (7, 10, 'sim');
INSERT INTO texto(pk_questao, pk_participante, resposta) VALUES (8, 10, 'não');