CREATE TABLE
    funcionario (
        pk_funcionario NUMBER (10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        nome VARCHAR2 (100) NOT NULL,
        gerente NUMBER (1) DEFAULT 0 NOT NULL,
        pk_gerente NUMBER DEFAULT NULL REFERENCES funcionario
    );

INSERT INTO
    funcionario (nome, gerente, pk_gerente)
VALUES
    ('Carlos Souza', 1, NULL);

INSERT INTO
    funcionario (nome, gerente, pk_gerente)
VALUES
    ('Ana Silva', 0, 1);

INSERT INTO
    funcionario (nome, gerente, pk_gerente)
VALUES
    ('Mariana Oliveira', 0, 1);

INSERT INTO
    funcionario (nome, gerente, pk_gerente)
VALUES
    ('Ricardo Lima', 0, 1);

INSERT INTO
    funcionario (nome, gerente, pk_gerente)
VALUES
    ('Fernanda Costa', 0, 1);

INSERT INTO
    funcionario (nome, gerente, pk_gerente)
VALUES
    ('Pedro Santos', 0, 1);

INSERT INTO
    funcionario (nome, gerente, pk_gerente)
VALUES
    ('Juliana Ferreira', 0, 1);

INSERT INTO
    funcionario (nome, gerente, pk_gerente)
VALUES
    ('Bruno Almeida', 0, 1);

INSERT INTO
    funcionario (nome, gerente, pk_gerente)
VALUES
    ('Tatiane Martins', 0, 1);

INSERT INTO
    funcionario (nome, gerente, pk_gerente)
VALUES
    ('Lucas Pereira', 0, 1);

CREATE TABLE
    metas (
        pk_metas NUMBER (10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        pk_funcionario NUMBER (10) REFERENCES funcionario,
        categoria VARCHAR2 (30) NOT NULL,
        data DATE NOT NULL,
        quantidade NUMBER NOT NULL,
        nota NUMBER CHECK (nota <= 100),
        data_avaliacao DATE,
        nota_final VARCHAR2 (5)
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        2,
        'seguros',
        date '2024-10-15',
        10,
        75,
        date '2025-02-01'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        2,
        'contas',
        date '2024-10-22',
        5,
        85,
        date '2025-02-10'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        2,
        'financiamentos',
        date '2024-09-30',
        8,
        90,
        date '2025-02-15'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        2,
        'empréstimo',
        date '2024-10-05',
        12,
        78,
        date '2025-02-20'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        3,
        'seguros',
        date '2024-10-10',
        7,
        82,
        date '2025-02-05'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        3,
        'contas',
        date '2024-10-14',
        9,
        88,
        date '2025-02-12'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        3,
        'financiamentos',
        date '2024-10-21',
        4,
        92,
        date '2025-02-18'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        3,
        'empréstimo',
        date '2024-10-12',
        15,
        76,
        date '2025-02-25'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        4,
        'seguros',
        date '2024-10-20',
        6,
        80,
        date '2025-02-03'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        4,
        'contas',
        date '2024-10-18',
        11,
        89,
        date '2025-02-08'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        4,
        'financiamentos',
        date '2024-10-02',
        5,
        91,
        date '2025-02-14'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        4,
        'empréstimo',
        date '2024-10-25',
        9,
        77,
        date '2025-02-22'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        5,
        'seguros',
        date '2024-10-05',
        8,
        84,
        date '2025-02-04'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        5,
        'contas',
        date '2024-10-11',
        10,
        86,
        date '2025-02-11'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        5,
        'financiamentos',
        date '2024-10-15',
        7,
        90,
        date '2025-02-16'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        5,
        'empréstimo',
        date '2024-10-18',
        14,
        79,
        date '2025-02-21'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        6,
        'seguros',
        date '2024-10-30',
        5,
        81,
        date '2025-02-02'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        6,
        'contas',
        date '2024-10-01',
        6,
        87,
        date '2025-02-09'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        6,
        'financiamentos',
        date '2024-10-10',
        9,
        93,
        date '2025-02-17'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        6,
        'empréstimo',
        date '2024-10-01',
        11,
        74,
        date '2025-02-26'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        7,
        'seguros',
        date '2024-10-25',
        12,
        83,
        date '2025-02-06'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        7,
        'contas',
        date '2024-10-30',
        7,
        88,
        date '2025-02-13'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        7,
        'financiamentos',
        date '2024-10-13',
        10,
        94,
        date '2025-02-19'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        7,
        'empréstimo',
        date '2024-10-20',
        13,
        76,
        date '2025-02-27'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        8,
        'seguros',
        date '2024-10-15',
        9,
        79,
        date '2025-02-07'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        8,
        'contas',
        date '2024-10-27',
        4,
        85,
        date '2025-02-15'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        8,
        'financiamentos',
        date '2024-10-05',
        8,
        91,
        date '2025-02-20'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        8,
        'empréstimo',
        date '2024-10-15',
        6,
        82,
        date '2025-02-28'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        9,
        'seguros',
        date '2024-10-12',
        11,
        77,
        date '2025-02-08'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        9,
        'contas',
        date '2024-10-18',
        3,
        84,
        date '2025-02-14'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        9,
        'financiamentos',
        date '2024-09-24',
        5,
        89,
        date '2025-02-21'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        9,
        'empréstimo',
        date '2024-10-30',
        7,
        73,
        date '2025-02-26'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        11,
        'seguros',
        date '2024-09-05',
        10,
        80,
        date '2025-02-10'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        11,
        'contas',
        date '2024-10-20',
        8,
        86,
        date '2025-02-16'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        11,
        'financiamentos',
        date '2024-10-17',
        12,
        88,
        date '2025-02-22'
    );

INSERT INTO
    metas (
        pk_funcionario,
        categoria,
        data,
        quantidade,
        nota,
        data_avaliacao
    )
VALUES
    (
        11,
        'empréstimo',
        date '2024-10-10',
        14,
        76,
        date '2025-02-27'
    );